services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: projetosaude_db
    restart: always
    environment:
      POSTGRES_USER: saude_user
      POSTGRES_PASSWORD: saude_password_dev
      POSTGRES_DB: projetosaude_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U saude_user -d projetosaude_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
